"use client";

import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import NoiseBackground from "@/components/ui/noise-background";

export default function TermsAndConditions() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-[#0a0a0b] text-zinc-100 relative">
      <div className="fixed inset-0 z-0">
        <NoiseBackground />
      </div>
      <div className="max-w-3xl mx-auto px-6 py-12 relative z-10">
        <Button
          variant="ghost"
          onClick={() => router.back()}
          className="mb-8 text-zinc-400 hover:text-zinc-100 -ml-2"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>

        <h1 className="text-4xl font-light tracking-tight mb-8">Terms and Conditions</h1>

        <p className="text-zinc-400 mb-8">Last updated: December 2025</p>

        <div className="space-y-8 text-zinc-300">
          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Prompt Architect, you accept and agree to be bound by these Terms and Conditions.
              If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">2. Description of Service</h2>
            <p>
              Prompt Architect is an AI-powered tool that transforms your ideas into production-ready prompts
              optimized for AI coding agents such as Claude, Cursor, and similar tools. Our service helps you
              create detailed specifications and prompts for software development projects.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">3. User Accounts</h2>
            <p className="mb-3">When you create an account with us:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You must provide accurate and complete information</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must notify us immediately of any unauthorized access</li>
              <li>You may not share your account with others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to use Prompt Architect to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Generate content that is illegal, harmful, or violates third-party rights</li>
              <li>Attempt to reverse-engineer or extract our AI models or algorithms</li>
              <li>Overload, disrupt, or interfere with our service</li>
              <li>Use automated scripts or bots without our permission</li>
              <li>Violate any applicable laws or regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">5. AI-Generated Content</h2>
            <p className="mb-3">Regarding the prompts and content generated by our service:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>AI-generated content is provided &quot;as is&quot; without warranties of any kind</li>
              <li>You are responsible for reviewing and validating generated content before use</li>
              <li>We do not guarantee the accuracy, completeness, or suitability of generated prompts</li>
              <li>Generated content may require modification for your specific use case</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">6. Intellectual Property</h2>
            <p className="mb-3">
              <strong className="text-zinc-100">Your Content:</strong> You retain ownership of the ideas and descriptions you submit.
              You grant us a license to process this content to provide our service.
            </p>
            <p>
              <strong className="text-zinc-100">Generated Prompts:</strong> The prompts generated for you are yours to use.
              However, similar prompts may be generated for other users based on similar inputs.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Prompt Architect shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages, including but not limited to loss of profits,
              data, or business opportunities, arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">8. Disclaimer of Warranties</h2>
            <p>
              The service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
              whether express or implied, including but not limited to implied warranties of merchantability,
              fitness for a particular purpose, and non-infringement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">9. Service Modifications</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue any part of the service at any time
              without prior notice. We may also update these terms from time to time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">10. Termination</h2>
            <p>
              We may terminate or suspend your access to the service immediately, without prior notice,
              for any reason, including breach of these Terms. Upon termination, your right to use the
              service will cease immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable laws,
              without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-medium text-zinc-100 mb-3">12. Contact Us</h2>
            <p>
              If you have any questions about these Terms and Conditions, please contact us at{" "}
              <a href="mailto:support@promptarchitect.com" className="text-amber-500 hover:text-amber-400">
                support@promptarchitect.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
